server:
   port: 8043
   context-path: /uaa
logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: oauth-server
security:
  oauth2:
    resource:
      serviceId: ${PREFIX:}resource
      # refer to: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter
      filter-order: 3
      